name: flutter_toolkit
description: "A new Flutter package project."
version: 0.0.3+2
homepage:

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ">=2.0.0 <=3.0.0"
  flutter_animate: ">=4.0.0 <=5.0.0"
  collection: '>=1.18.0 <2.0.0'
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
